# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_metadata_widget.ui'
#
# Created: Sun Mar 16 11:54:52 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BasicMetadata(object):
    def setupUi(self, BasicMetadata):
        BasicMetadata.setObjectName(_fromUtf8("BasicMetadata"))
        BasicMetadata.resize(817, 656)
        BasicMetadata.setStyleSheet(_fromUtf8("QGroupBox\n"
"{ \n"
"    border: 1px solid #A6A6A6; \n"
"    border-radius: 5px; \n"
"}"))
        self.gridLayout_2 = QtGui.QGridLayout(BasicMetadata)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(BasicMetadata)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtGui.QLabel(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.titleInput = QtGui.QLineEdit(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleInput.sizePolicy().hasHeightForWidth())
        self.titleInput.setSizePolicy(sizePolicy)
        self.titleInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleInput.setFont(font)
        self.titleInput.setAlignment(QtCore.Qt.AlignCenter)
        self.titleInput.setObjectName(_fromUtf8("titleInput"))
        self.gridLayout_2.addWidget(self.titleInput, 0, 1, 1, 3)
        self.label_2 = QtGui.QLabel(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.subtitleInput = QtGui.QLineEdit(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtitleInput.sizePolicy().hasHeightForWidth())
        self.subtitleInput.setSizePolicy(sizePolicy)
        self.subtitleInput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.subtitleInput.setFont(font)
        self.subtitleInput.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitleInput.setObjectName(_fromUtf8("subtitleInput"))
        self.gridLayout_2.addWidget(self.subtitleInput, 1, 1, 1, 3)
        self.groupBox = QtGui.QGroupBox(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.authorInput = QtGui.QLineEdit(self.groupBox)
        self.authorInput.setObjectName(_fromUtf8("authorInput"))
        self.gridLayout_3.addWidget(self.authorInput, 0, 1, 1, 1)
        self.authorFileAsInput = QtGui.QLineEdit(self.groupBox)
        self.authorFileAsInput.setObjectName(_fromUtf8("authorFileAsInput"))
        self.gridLayout_3.addWidget(self.authorFileAsInput, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.addAuthorButton = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAuthorButton.sizePolicy().hasHeightForWidth())
        self.addAuthorButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/basic_metadata_widget/resources/images/add_16x16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addAuthorButton.setIcon(icon)
        self.addAuthorButton.setIconSize(QtCore.QSize(16, 16))
        self.addAuthorButton.setObjectName(_fromUtf8("addAuthorButton"))
        self.gridLayout_3.addWidget(self.addAuthorButton, 2, 0, 1, 2)
        self.authorsList = ExtendedQListWidget(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorsList.sizePolicy().hasHeightForWidth())
        self.authorsList.setSizePolicy(sizePolicy)
        self.authorsList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.authorsList.setObjectName(_fromUtf8("authorsList"))
        self.gridLayout_3.addWidget(self.authorsList, 0, 2, 3, 1)
        self.gridLayout_2.addWidget(self.groupBox, 3, 1, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.coverImage = ExtendedQLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coverImage.sizePolicy().hasHeightForWidth())
        self.coverImage.setSizePolicy(sizePolicy)
        self.coverImage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.coverImage.setScaledContents(True)
        self.coverImage.setAlignment(QtCore.Qt.AlignCenter)
        self.coverImage.setWordWrap(True)
        self.coverImage.setObjectName(_fromUtf8("coverImage"))
        self.verticalLayout_4.addWidget(self.coverImage)
        self.frame_7 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet(_fromUtf8(""))
        self.frame_7.setFrameShape(QtGui.QFrame.Panel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_12 = QtGui.QLabel(self.frame_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.coverModificationInput = QtGui.QComboBox(self.frame_7)
        self.coverModificationInput.setObjectName(_fromUtf8("coverModificationInput"))
        self.gridLayout_5.addWidget(self.coverModificationInput, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
        self.coverDesignerInput = QtGui.QLineEdit(self.frame_7)
        self.coverDesignerInput.setObjectName(_fromUtf8("coverDesignerInput"))
        self.gridLayout_5.addWidget(self.coverDesignerInput, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.horizontalLayout.addWidget(self.frame)
        self.label_6 = QtGui.QLabel(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.synopsisInput = QtGui.QPlainTextEdit(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.synopsisInput.sizePolicy().hasHeightForWidth())
        self.synopsisInput.setSizePolicy(sizePolicy)
        self.synopsisInput.setFrameShape(QtGui.QFrame.StyledPanel)
        self.synopsisInput.setObjectName(_fromUtf8("synopsisInput"))
        self.horizontalLayout.addWidget(self.synopsisInput)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 1, 1, 3)
        self.label_7 = QtGui.QLabel(BasicMetadata)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.languageInput = QtGui.QComboBox(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageInput.sizePolicy().hasHeightForWidth())
        self.languageInput.setSizePolicy(sizePolicy)
        self.languageInput.setObjectName(_fromUtf8("languageInput"))
        self.gridLayout_2.addWidget(self.languageInput, 2, 1, 1, 1)
        self.idInput = QtGui.QLineEdit(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idInput.sizePolicy().hasHeightForWidth())
        self.idInput.setSizePolicy(sizePolicy)
        self.idInput.setMaximumSize(QtCore.QSize(50, 16777215))
        self.idInput.setObjectName(_fromUtf8("idInput"))
        self.gridLayout_2.addWidget(self.idInput, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(BasicMetadata)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 2, 1, 1)

        self.retranslateUi(BasicMetadata)
        QtCore.QMetaObject.connectSlotsByName(BasicMetadata)
        BasicMetadata.setTabOrder(self.titleInput, self.subtitleInput)
        BasicMetadata.setTabOrder(self.subtitleInput, self.languageInput)
        BasicMetadata.setTabOrder(self.languageInput, self.idInput)
        BasicMetadata.setTabOrder(self.idInput, self.authorInput)
        BasicMetadata.setTabOrder(self.authorInput, self.authorFileAsInput)
        BasicMetadata.setTabOrder(self.authorFileAsInput, self.addAuthorButton)
        BasicMetadata.setTabOrder(self.addAuthorButton, self.authorsList)
        BasicMetadata.setTabOrder(self.authorsList, self.coverModificationInput)
        BasicMetadata.setTabOrder(self.coverModificationInput, self.coverDesignerInput)
        BasicMetadata.setTabOrder(self.coverDesignerInput, self.synopsisInput)

    def retranslateUi(self, BasicMetadata):
        self.label_5.setText(_translate("BasicMetadata", "Cubierta", None))
        self.label_3.setText(_translate("BasicMetadata", "Autores", None))
        self.label.setText(_translate("BasicMetadata", "Título", None))
        self.label_2.setText(_translate("BasicMetadata", "Subtítulo", None))
        self.label_4.setText(_translate("BasicMetadata", "Nombre", None))
        self.label_9.setText(_translate("BasicMetadata", "Mostrar como", None))
        self.addAuthorButton.setText(_translate("BasicMetadata", "Agregar Autor", None))
        self.coverImage.setText(_translate("BasicMetadata", "<html><head/><body><p><span style=\" text-decoration: underline; color:#0000ff;\">Haga click aquí para seleccionar la imagen de cubierta</span></p></body></html>", None))
        self.label_12.setText(_translate("BasicMetadata", "Modificación", None))
        self.label_13.setText(_translate("BasicMetadata", "Diseñador", None))
        self.label_6.setText(_translate("BasicMetadata", "Sinopsis", None))
        self.label_7.setText(_translate("BasicMetadata", "Idioma", None))
        self.label_8.setText(_translate("BasicMetadata", "ID", None))

from gui.custom_widgets import ExtendedQLabel, ExtendedQListWidget
from . import basic_metadata_widget_rc
